### ISSUE TITLE
Not compile in ubuntu 20.04. You can made a release bin please? 

### ISSUE THREAD

**Issue by sirlordt** [magiblot/tvterm#1]
/home/linuxbrew/.linuxbrew/bin/ld: libtvterm-core.a(unity_0_cxx.cxx.o): warning: relocation against `_ZN6tvterm16TerminalActivity13inputWaitStepE' in read-only section `.text'
/home/linuxbrew/.linuxbrew/bin/ld: libtvterm-core.a(unity_0_cxx.cxx.o): in function `tvterm::TerminalActivity::advanceWaitState(int, bool)':
unity_0_cxx.cxx:(.text+0x5d9d): undefined reference to `tvterm::TerminalActivity::maxReadTime'
/home/linuxbrew/.linuxbrew/bin/ld: unity_0_cxx.cxx:(.text+0x5eb3): undefined reference to `tvterm::TerminalActivity::inputWaitStep'
/home/linuxbrew/.linuxbrew/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/tvterm.dir/build.make:108: tvterm] Error 1
make[1]: *** [CMakeFiles/Makefile2:155: CMakeFiles/tvterm.dir/all] Error 2

![imagen](https://user-images.githubusercontent.com/4441192/144903766-424e5913-a64c-43cc-9b19-98afc9518cc7.png)

![imagen](https://user-images.githubusercontent.com/4441192/144904374-b4b3902b-1393-4807-8570-27a57d14cb5f.png)

**Comment by magiblot** [comment]
Hola Tomás, sorry for the wait. I have pushed a fix for this. Just run `git pull` to get it, and compilation should then work.

It is not safe to make a binary release for Linux because we may be using different versions of the dynamically-linked dependencies.

Saludos.

**Comment by sirlordt** [comment]
Excellent. it works now!!!! Thanks!!!!

![image](https://user-images.githubusercontent.com/4441192/145246643-c855eb76-8d5f-49d4-852f-2985506c54bb.png)

**Comment by sirlordt** [comment]
> Hola Tomás, sorry for the wait. I have pushed a fix for this. Just run `git pull` to get it, and compilation should then work.
> 
> It is not safe to make a binary release for Linux because we may be using different versions of the dynamically-linked dependencies.

I mean a static linked version of the executable like golang. In my projects with cmake i used:

target_link_options(main PRIVATE --static -static-libgcc -static-libstdc++)

![image](https://user-images.githubusercontent.com/4441192/145247720-92c4d812-29b4-46c1-b02f-5f31209b1bed.png)

> 
> Saludos.

**Comment by magiblot** [comment]
I tried to generate the static binary (https://github.com/magiblot/tvterm/commit/4804df167337fb86abcf4a149e919e986e3508de, not in master); I thought it would be harder since I needed the static version (`.a`) of all dependent libraries but Ubuntu provides them. However, the program crashes while running glibc code, probably because glibc appears to be loading some of its functions dynamically at runtime:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff78f96e4 in __nss_readline () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff78f96e4 in __nss_readline () from /usr/lib/libc.so.6
#1  0x00007ffff79aa18d in ?? () from /usr/lib/libnss_files.so.2
#2  0x00007ffff79aa44c in _nss_files_getgrnam_r () from /usr/lib/libnss_files.so.2
#3  0x000000000061170d in getgrnam_r ()
#4  0x00000000005e8bdd in grantpt ()
#5  0x00000000004a06ab in openpty ()
#6  0x00000000004a0427 in forkpty ()
#7  0x00000000004276f5 in tvterm::createPty (size=..., doAsChild=@0x414b54: {void (void)} 0x414b54 <tvterm::VTermAdapter::childActions()>, 
    onError=@0x406017: {void (const char *)} 0x406017 <onTermError(char const*)>) at /home/runner/work/tvterm/tvterm/source/tvterm-core/pty.cc:34
#8  0x000000000040847d in tvterm::TerminalActivity::create (size=..., createTerminal=
    @0x407920: {tvterm::TerminalAdapter &(TPoint, tvterm::TerminalSharedState &)} 0x407920 <tvterm::VTermAdapter::create(TPoint, tvterm::TerminalSharedState&)>, childActions=@0x414b54: {void (void)} 0x414b54 <tvterm::VTermAdapter::childActions()>, 
    onError=@0x406017: {void (const char *)} 0x406017 <onTermError(char const*)>, threadPool=...)
    at /home/runner/work/tvterm/tvterm/source/tvterm-core/termactiv.cc:31
#9  0x00000000004060bd in TVTermApp::newTerm (this=0x7fffffffe2e0) at /home/runner/work/tvterm/tvterm/source/tvterm/app.cc:184
#10 0x0000000000404eaf in TVTermApp::TVTermApp (this=0x7fffffffe2e0, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /home/runner/work/tvterm/tvterm/source/tvterm/app.cc:54
#11 0x0000000000404bd1 in main () at /home/runner/work/tvterm/tvterm/source/tvterm/app.cc:38
```

If you are interested, you can download the `tvterm-linux-x86_64` artifact from https://github.com/magiblot/tvterm/actions/runs/1555734832 and try to run the application.

**Comment by sirlordt** [comment]
Try with g++10. I used g++11 from external ppa.

**Comment by sirlordt** [comment]
@magiblot In this days i used redis++. I found a "bug" that generate a segmentation fault. Very similar to this issue. sewenew the library maintainer of redis-plus-plus, discover the problem is in the pthread when is linked with -static option.

The solutions to redis++:

g++ -std=c++17 -static -o app app.cpp **-Wl,--whole-archive** -lpthread **-Wl,--no-whole-archive**

[stdthread-with-static-linking-causes-segmentation-fault](https://stackoverflow.com/questions/9002264/starting-a-stdthread-with-static-linking-causes-segmentation-fault)

Maybe the problem is similar but with the library libnss?.

**Comment by magiblot** [comment]
Hi Tomás! I have been looking into this since your comment and I have come to the conclusion that it is not possible to link statically against GNU's forkpty, for the reasons exposed [here](https://sourceware.org/glibc/wiki/FAQ#Even_statically_linked_programs_need_some_shared_libraries_which_is_not_acceptable_for_me.__What_can_I_do.3F). This means that the `--whole-archive` option can't solve this issue.

The only way I can think of producing a working static binary is to replace glibc with another libc implementation which doesn't suffer from these problems, such as musl. Using musl instead of glibc requires rebuilding not only this application, but also all of its dependencies. So it is not possible, for example, to reuse the static libraries bundled with Ubuntu's `-dev` packages since they contain references to glibc-specific symbols.

**Comment by sirlordt** [comment]
@magiblot  Ok. Thanks for you feedback!!!!!.
